name: whw_gridded_data
channels:
  - conda-forge
dependencies:
  - python=3.6
  - ipython
  - ipykernel
  - requests
  - geopandas
  - matplotlib
  - seaborn
  - cartopy
  - ulmo
  - owslib
  - xlrd
  - seaborn
  - xarray
  - rasterio
  - dask
  - pandas
